export const LOAD_INSTANCE = 'LOAD_INSTANCE';
export const KILL_INSTANCE = 'KILL_INSTANCE';
export const PING_INSTANCE = 'PING_INSTANCE';
export const LOAD_SERVER_SELECT_INSTANCE = 'LOAD_SERVER_SELECT_INSTANCE';
